package com.perfectlypressed.android.analytics

object EventName {
    const val APPLICATION_OPENED = "application_opened"
    const val APPLICATION_UPDATED = "application_updated"
    const val APPLICATION_NOT_UPDATED = "application_not_updated"
    const val ON_BOARDING_VIEWED = "onboarding_viewed"
    const val SCREEN_VIEWED = "screen_viewed"
    const val LANGUAGE_SELECTED = "language_selected"
    const val BIOMETRIC = "biometric"
    const val SCREEN_VIEW = "screen_viewed"
    const val STEP_PERFORMED = "step_performed"
    const val USER_DETAIL_SAVED = "user_detail_saved"
    const val CTA_CLICKED = "cta_clicked"
    const val PASSWORD_SET = "password_set"
    const val DISCOUNT_APPLIED = "discount_applied"
    const val ACCOUNT_TYPE_SELECTED = "account_type_selected"
    const val ACCOUNT_DELETED = "account_deleted"
    const val ACCOUNT_SETUP_COMPLETED = "account_setup_completed"
    const val REGISTERED = "registered"
    const val ARRIVED_IN_HARAM = "arrived_in_haram"
    const val USER_LOGIN = "Logged_In"
    const val ACCOUNT_MERGED = "account_merged"
    const val HOME_VIEWED = "home_viewed"
    const val QUIZ_VIEWED = "quiz_viewed"
    const val QUIZ_ANSWERED = "quiz_answered"
    const val QUIZ_COMPLETED = "quiz_completed"
    const val PLEDGE_TAKEN = "pledge_taken"
    const val ORDER_INITIATED = "order_created"
    const val ORDER_PAYMENT_DONE = "payment_done"
    const val UMRAH_ACCEPTED_ORDER = "umrah_order_accepted"
    const val PERFORMER_REJECTED_ORDER = "performer_rejected_order"
    const val SEEKER_ACCEPTED_PERFORMER = "order_accepted"
    const val SEEKER_REJECTED_PERFORMER = "order_rejected"
    const val SUPPLICATION_ADDED = "supplication_added"
    const val REQUEST_VIEWED = "request_viewed"
    const val REQUEST_DELETED = "request_deleted"
    const val STEP_COMPLETED = "step_completed"
    const val STEP = "step"
    const val SEEKER_TRACKING = "seeker_tracking"
    const val VIEWED_USER_DETAILS_SCREEN = "viewed_user_details_screen"
    const val SERVICE_COMPLETED = "service_completed"
    const val AUDIO_INTENTION_RECORDED = "audio_intention_recorded"
    const val AUDIO_INTENTION_DELETED = "audio_intention_deleted"
    const val PLAY_AUDIO_INTENTION = "audio_started"
    const val PAUSE_AUDIO_INTENTION = "audio_stop"
    const val RESUME_AUDIO_INTENTION = "resume_audio_intention"
    const val STOP_AUDIO_INTENTION = "stop_audio_intention"
    const val SEEKER_RATED_PERFORMER = "seeker_rated_performer"
    const val SEEKER_CANCELLED_ORDER = "seeker_cancelled_order"
    const val PERFORMER_CANCELLED_ORDER = "performer_cancelled_order"
    const val LANGUAGE_DIALOG = "Language Selection Dialog"
    const val CTA_LANGUAGE_SELECTED = "language_selected"
    const val PAYMENT_COMPLETED = "payment_completed"
    const val UMRAH_SCHEDULE_ADDED = "request_added"
    const val UMRAH_SCHEDULE_DELETED = "umrah_schedule_deleted"
    const val IMAGE_UPLOADED = "image_uploaded"
}

object EventConstants {
    const val NON_ANALYTICAL_INTEGER = Int.MIN_VALUE
    const val NON_ANALYTICAL_FLOAT = Float.MIN_VALUE
    const val NON_ANALYTICAL_DOUBLE = Double.MIN_VALUE
    const val NON_ANALYTICAL_LONG = Long.MIN_VALUE
    const val NON_ANALYTICAL_EMPTY_STRING = "NON_ANALYTICAL_EMPTY_STRING"
}

object CTANames {

    const val SEEKER_UMRAH_SELECTED_TIME_OKAY_CTA = "seeker_umrah_selected_time_okay_cta"
    const val PERFORMER_UMRAH_SELECT_TIME_POP_UP_CTA = "performer_umrah_select_time_popup_cta"
    const val PERFORMER_TIME_SUBMITTED_OKAY_CTA = "performer_time_submitted_okay_cta"
    const val SEEKER_OFFER_TAP_BAR = "tab_bar_offer_cta"
    const val SELECT_N_PAY = "select_n_pay"
    const val STAR = "star"
    const val INTENTION = "intention"
    const val SPOKEN_LANGUAGE = "spoken_language"
    const val USER_PERFORMER = "user_detail_performer"
    const val SEEKER_REQUEST_TAP_BAR = "tab_bar_request_cta"
    const val PERFORMER_TRACKING = "performer_tracking"
    const val PERFORMER_SCHEDULE_TAP_BAR = "schedule_list"
    const val DELETE = "delete_popup"
    const val CHAT_List = "chat_list"
    const val CHAT_ITEM = "chat_item"
    const val CHAT_MESSAGE = "chat_item"
    const val DISCOUNT = "discount_popup"
    const val SEEKER_OFFERS_OFFERS_LIST = "offer_list_seeker"
    const val PERFORMER_SCHEDULED_LIST = "schedule_list"
    const val REQUEST_UMRAH_DETAIL = "request_umrah_detail"
    const val REQUEST_UMRAH = "request_umrah"
    const val REQUEST_UMRAH_POPUP = "request_umrah_popup"
    const val SEEKER_TRACKING = "seeker_track"
    const val SEEKER_OFFER_ITEM_SELECTED = "offers_item"
    const val SEEKER_START_TRACKING = "seeker_start_tracking"
    const val SEEKER_OFFER_FILTER_ITEM_CLICKED = "filter"
    const val SEEKER_OFFER_FILTER_SCREEN = "filter_popup"
    const val SEEKER_OFFER_FILTER_APPLIED_CTA = "apply"
    const val SEEKER_OFFER_UMRAH_DETAILS = "offer_umrah_detail"
    const val SEEKER_OFFER_UMRAH_CONTINUE_PAYMENT_CTA = "continue"
    const val SEEKER_OFFER_UMRAH_INVOICE_SCREEN = "offer_umrah_invoice_detail"
    const val SEEKER_OFFER_UMRAH_INVOICE_CONTINUE_CTA = "continue_payment"
    const val SEEKER_OFFER_PAYMENT_SCREEN = "offer_payment_screen"
    const val SEEKER_PAYMENT_SCREEN = "payment_invoice"
    const val SEEKER_INVOICE= "seeker_invoice"
    const val SEEKER_OFFER_CARD_DETAIL_SCREEN = "offer_card_detail_screen"
    const val SEEKER_CARD_DETAILS= "card_details"
    const val SEEKER_DETAILS= "seeker_details"
    const val SEEKER_OFFER_CARD_DETAIL_PAY_NOW_CTA = "offer_card_detail_pay_now_cta"
    const val PERFORMER_UMRAH_REQUEST_CTA = "home_umrah_perform_request_cta"
    const val NEW_UMRAH_REJECT_ORDER = "new_umrah_order_popup"
    const val UMRAH_CANCELLED_CTA = "umrah_cancelled"
    const val PERFORMER_DASHBOARD = "dashboard"
    const val REMINDER_POPUP = "reminder_popup"
    const val PERFORM = "perform"
    const val PERFORMER = "performer"
    const val CANCEL = "cancel"
    const val PERFORMER_OFFER_REQUEST_POPUP_ADD_CTA = "add_now"
    const val PERFORMER_OFFER_ADD_REQUEST = "add_request"
    const val SEEKER_ORDER_JOURNEY_SCREEN_NAME = "seeker_order_journey"
    const val ONBOARDING_FULL_SCREEN = "fullscreen"
    const val ONBOARDING_SCREEN = "onboarding"
    const val ONBOARDING_CONTINUE_CTA = "continue"

}